
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-10T15:31:44+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "4f94b01fb085880f5aafb9e6d91d960387538492",
 "version": "1.19.0+2.g4f94b01.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
